# Generated by Django 5.0.7 on 2024-07-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories_delete_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='total',
        ),
        migrations.AddField(
            model_name='categories',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
